// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOpezdqQ44YAk8NDyGisj12z-74R9WGU0',
    appId: '1:455425930657:web:e6f748e79158cf1b8107e0',
    messagingSenderId: '455425930657',
    projectId: 'lab-13-1-3155f',
    authDomain: 'lab-13-1-3155f.firebaseapp.com',
    storageBucket: 'lab-13-1-3155f.appspot.com',
    measurementId: 'G-2VBYVY3EEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RSzB7Yx0ue9bf-SzMQIOswdM4cggU7k',
    appId: '1:455425930657:android:d8f25e96b6b40d7d8107e0',
    messagingSenderId: '455425930657',
    projectId: 'lab-13-1-3155f',
    storageBucket: 'lab-13-1-3155f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7kuvef8yf8A_IRnzyKII_uxru0EIxDQ',
    appId: '1:455425930657:ios:78b55c4f8d666b0c8107e0',
    messagingSenderId: '455425930657',
    projectId: 'lab-13-1-3155f',
    storageBucket: 'lab-13-1-3155f.appspot.com',
    iosClientId: '455425930657-4ik3spo9d7c8er2p98hfibj54mio1ia3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab131',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7kuvef8yf8A_IRnzyKII_uxru0EIxDQ',
    appId: '1:455425930657:ios:78b55c4f8d666b0c8107e0',
    messagingSenderId: '455425930657',
    projectId: 'lab-13-1-3155f',
    storageBucket: 'lab-13-1-3155f.appspot.com',
    iosClientId: '455425930657-4ik3spo9d7c8er2p98hfibj54mio1ia3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab131',
  );
}
